(define-module (lp packages rust-apps)
  #:use-module (gnu packages commencement)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages crates-compression)
  #:use-module (gnu packages crates-graphics)
  #:use-module (gnu packages crates-io)
  #:use-module (gnu packages crates-windows)
  #:use-module (gnu packages curl)
  #:use-module (gnu packages perl)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages ssh)
  #:use-module (gnu packages tls)
  #:use-module (lp packages)
  #:use-module (lp packages crates-extra)
  #:use-module (lp packages crates-openssl)
  #:use-module (guix git-download)
  #:use-module (guix download)
  #:use-module (guix build-system cargo)
  #:use-module (guix packages)
  #:use-module (guix utils)
  #:use-module ((guix licenses)
                #:prefix license:))

(module-define!
 (resolve-module '(gnu packages crates-io))
                 'rust-openssl-sys-0.9
                 rust-openssl-sys-0.9.104)

(define-public zellij-0.40
  (package
    (name "zellij")
    (version "0.41.2")
    (source
     (origin
       (method url-fetch)
       (uri (crate-uri "zellij" version))
       (file-name (string-append name "-" version ".tar.gz"))
       (sha256
        (base32 "10c35pw25i2g6j8dd4vx6vzl3y6rr1rivvci04zkyq09w5wpk8xk"))))
    (build-system cargo-build-system)
    (arguments
     `(#:tests? #f ; no tests
       #:install-source? #f
       #:cargo-inputs (("rust-dialoguer" ,rust-dialoguer-0.10)
                       ("rust-log" ,rust-log-0.4)
                       ("rust-names" ,rust-names-0.14)
                       ("rust-suggest" ,rust-suggest-0.4)
                       ("rust-thiserror" ,rust-thiserror-1)
                       ("rust-zellij-client" ,rust-zellij-client-0.41)
                       ("rust-zellij-server" ,rust-zellij-server-0.41)
                       ("rust-zellij-utils" ,rust-zellij-utils-0.41))
       #:cargo-development-inputs (("rust-insta" ,rust-insta-1)
                                   ("rust-rand" ,rust-rand-0.8)
                                   ("rust-regex" ,rust-regex-1)
                                   ("rust-ssh2" ,rust-ssh2-0.9))))
    (native-inputs
     (list pkg-config gcc-toolchain))
    (inputs
     (list zlib openssl curl libssh2 perl (list zstd "lib")))
    (home-page "https://zellij.dev")
    (synopsis "Terminal workspace with batteries included")
    (description
     "This package provides a terminal workspace with batteries included.")
    (license license:expat)))

(define-public dust-1
  (package
    (name "dust")
    (version "1.1.2")
    (source
     (origin
       (method url-fetch)
       (uri (crate-uri "du-dust" version))
       (file-name (string-append name "-" version ".tar.gz"))
       (sha256
        (base32 "1ilqns5j1177mvc9hnxdzlgdqgs978cfnj61yh0gk0iy4ajfqhbm"))))
    (build-system cargo-build-system)
    (arguments
     `(#:install-source? #f
       #:cargo-inputs (("rust-ansi-term" ,rust-ansi-term-0.12)
                       ("rust-chrono" ,rust-chrono-0.4)
                       ("rust-clap" ,rust-clap-4)
                       ("rust-clap-complete" ,rust-clap-complete-4)
                       ("rust-clap-mangen" ,rust-clap-mangen-0.2)
                       ("rust-config-file" ,rust-config-file-0.2)
                       ("rust-ctrlc" ,rust-ctrlc-3)
                       ("rust-directories" ,rust-directories-4)
                       ("rust-filesize" ,rust-filesize-0.2)
                       ("rust-lscolors" ,rust-lscolors-0.13)
                       ("rust-rayon" ,rust-rayon-1)
                       ("rust-regex" ,rust-regex-1)
                       ("rust-serde" ,rust-serde-1)
                       ("rust-serde-json" ,rust-serde-json-1)
                       ("rust-stfu8" ,rust-stfu8-0.2)
                       ("rust-sysinfo" ,rust-sysinfo-0.27)
                       ("rust-terminal-size" ,rust-terminal-size-0.2)
                       ("rust-thousands" ,rust-thousands-0.2)
                       ("rust-unicode-width" ,rust-unicode-width-0.1)
                       ("rust-winapi-util" ,rust-winapi-util-0.1))
       #:cargo-development-inputs (("rust-assert-cmd" ,rust-assert-cmd-2)
                                   ("rust-tempfile" ,rust-tempfile-3))))
    (home-page "https://github.com/bootandy/dust")
    (synopsis "More intuitive version of du")
    (description "This package provides a more intuitive version of du.")
    (license license:asl2.0)))

(define-public texlab-4
  (package
    (name "texlab")
    (version "4.3.2")
    (source
     (origin
       (method url-fetch)
       (uri (crate-uri "texlab" version))
       (file-name (string-append name "-" version ".tar.gz"))
       (sha256
        (base32 "0laxg7qprbixp20cqdy824vrxq692c2x92aqigw5a84s0b69dbrn"))))
    (build-system cargo-build-system)
    (arguments
     `(#:tests? #f ; no tests
       #:install-source? #f
       #:cargo-inputs (("rust-anyhow" ,rust-anyhow-1)
                       ("rust-byteorder" ,rust-byteorder-1)
                       ("rust-chrono" ,rust-chrono-0.4)
                       ("rust-clap" ,rust-clap-4)
                       ("rust-crossbeam-channel" ,rust-crossbeam-channel-0.5)
                       ("rust-dashmap" ,rust-dashmap-5)
                       ("rust-derive-more" ,rust-derive-more-0.99)
                       ("rust-dirs" ,rust-dirs-4)
                       ("rust-encoding-rs" ,rust-encoding-rs-0.8)
                       ("rust-encoding-rs-io" ,rust-encoding-rs-io-0.1)
                       ("rust-fern" ,rust-fern-0.6)
                       ("rust-flate2" ,rust-flate2-1)
                       ("rust-fuzzy-matcher" ,rust-fuzzy-matcher-0.3)
                       ("rust-human-name" ,rust-human-name-2)
                       ("rust-isocountry" ,rust-isocountry-0.3)
                       ("rust-itertools" ,rust-itertools-0.10)
                       ("rust-log" ,rust-log-0.4)
                       ("rust-logos" ,rust-logos-0.12)
                       ("rust-lsp-server" ,rust-lsp-server-0.6)
                       ("rust-lsp-types" ,rust-lsp-types-0.93)
                       ("rust-notify" ,rust-notify-5)
                       ("rust-once-cell" ,rust-once-cell-1)
                       ("rust-petgraph" ,rust-petgraph-0.6)
                       ("rust-regex" ,rust-regex-1)
                       ("rust-rowan" ,rust-rowan-0.15)
                       ("rust-rustc-hash" ,rust-rustc-hash-1)
                       ("rust-serde" ,rust-serde-1)
                       ("rust-serde-json" ,rust-serde-json-1)
                       ("rust-serde-millis" ,rust-serde-millis-0.1)
                       ("rust-serde-regex" ,rust-serde-regex-1)
                       ("rust-serde-repr" ,rust-serde-repr-0.1)
                       ("rust-smol-str" ,rust-smol-str-0.1)
                       ("rust-strum" ,rust-strum-0.24)
                       ("rust-tempfile" ,rust-tempfile-3)
                       ("rust-threadpool" ,rust-threadpool-1)
                       ("rust-titlecase" ,rust-titlecase-2)
                       ("rust-typed-builder" ,rust-typed-builder-0.11)
                       ("rust-unicode-normalization" ,rust-unicode-normalization-0.1)
                       ("rust-url" ,rust-url-2)
                       ("rust-uuid" ,rust-uuid-1))
       #:cargo-development-inputs (("rust-assert-unordered" ,rust-assert-unordered-0.3)
                                   ("rust-criterion" ,rust-criterion-0.4)
                                   ("rust-env-logger" ,rust-env-logger-0.9)
                                   ("rust-insta" ,rust-insta-1)
                                   ("rust-jod-thread" ,rust-jod-thread-0.1))))
    (home-page "https://github.com/latex-lsp/texlab")
    (synopsis "LaTeX Language Server")
    (description "This package provides @code{LaTeX} Language Server.")
    (license license:gpl3)))
